/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratoriooscarsantiago;
import java.lang.*;
import java.awt.Point;
import java.awt.Point;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.audio.AudioPlayer;

/**
 *
 * @author Oscar
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */

    
    static Point c1=new Point(75, 40);
    static Point c2=new Point(75, 100);
    static Point c3=new Point(75, 200);
    static String ganadores="";
    static int puesto=0;
    static boolean bandera=true;
    static inicio fram;
    static hilocarro1 car1= new hilocarro1();
    static hilocarro2 car2= new hilocarro2();
    static hilocarro3 car3= new hilocarro3();
    static hiloInicio iniciar= new hiloInicio();
  
    
    
    public inicio() throws InterruptedException {
        initComponents();
        txtResultados1.setEditable(false);
    

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtResultados = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.png"))); // NOI18N
        getContentPane().add(carro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 300, 120));

        carro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.png"))); // NOI18N
        getContentPane().add(carro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 250, 130));

        carro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.png"))); // NOI18N
        getContentPane().add(carro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 250, 70));
        carro1.getAccessibleContext().setAccessibleDescription("");

        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(204, 255, 0), new java.awt.Color(255, 204, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 10, 350));

        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(204, 255, 0), new java.awt.Color(255, 204, 0)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 10, 350));

        txtResultados.setViewportView(txtResultados1);

        getContentPane().add(txtResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 210, 90));

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));
        jButton1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           if(!car1.isAlive() && !car2.isAlive() && !car3.isAlive()){ 
        
        txtResultados1.setText("");
            puesto=0;
            carro1.setLocation(c1);
            carro2.setLocation(c2);
            carro3.setLocation(c3);

            car1= new hilocarro1();
            car2= new hilocarro2();
            car3= new hilocarro3();
            car1.setName("carro1");
            car2.setName("carro2");
            car3.setName("carro3");
            

            car1.start();
            car2.start();
            car3.start();
        
        
           } 
        
        if (bandera) iniciar.start();
        bandera=false;
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        fram=new inicio();
        fram.setVisible(true);
        
        car1.join();
        car2.join();
        car3.join();
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel carro1 = new javax.swing.JLabel();
    public static final javax.swing.JLabel carro2 = new javax.swing.JLabel();
    public static final javax.swing.JLabel carro3 = new javax.swing.JLabel();
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane txtResultados;
    public static final javax.swing.JTextPane txtResultados1 = new javax.swing.JTextPane();
    // End of variables declaration//GEN-END:variables
}
